Fix: Toaster and useToast errors
The commit fixes the following errors:
- src/components/ui/toaster.tsx(12,11): error TS2339: Property 'toasts' does not exist on type '{ toast: ({ title, description, action, variant }: ToastProps) => void; }'.
- src/hooks/use-toast.ts(2,10): error TS2724: '"sonner"' has no exported member named 'Toast'. Did you mean 'toast'?